app: ServerMain.cpp global.cpp clientfd.cpp buffer.cpp  
	g++ ServerMain.cpp log.cpp sendfile.cpp tcpserver.cpp parse_data.cpp SaveAndPrintf_data.cpp global.cpp clientfd.cpp buffer.cpp testpack.cpp -lpthread -o app
